server:
  port: 8090

logging:
  config: classpath:logback-boot.xml

mybatis:
  type-aliases-package: com.blueprint.module.*.serviceDal.po
  mapper-locations: classpath:mybatis-mapper/**/*.xml

spring:
  application:
    name: blueprint
    #datasource
  datasource:
    name: era
    url: jdbc:mysql://localhost:3306/blueprint_dev?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    spring.datasource.filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000




